services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
  api:
    build: .
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      CORS_ORIGIN: ${CORS_ORIGIN}
    depends_on: [db]
    ports: ["3000:3000"]
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
volumes:
  dbdata:
